BrightspaceHypermediaComponents/foundation-components

components/activity/editor/d2l-activity-editor-sidebar.js
components/activity/editor/d2l-activity-editor.js

https://github.com/BrightspaceUI/core/pull/854
Removes now unnecessary styles.

Adjusted template based on core changes

---

components/activity/name/d2l-activity-name-learning-path.js
framework/hypermedia-lit-mixin.js
state/sirenComponents/Common.js
state/sirenComponents/SirenAction.js
state/sirenComponents/SirenLink.js
state/sirenComponents/SirenSubEntity.js
state/sirenComponents/sirenComponentFactory.js
state/store.js

This part enables us to do synced actions with the server. Where the server response is a hypermedia object.
Async coming in another PR.

First bit of the action work.

---

README.md
components/activity/description/README.md
components/activity/editor/README.md
components/activity/icon/README.md
components/activity/image/README.md
components/activity/item/README.md
components/activity/name/README.md
components/activity/type/README.md
creating-new-components.md

[US120235](https://rally1.rallydev.com/#/detail/userstory/424740820104?fdp=true)
- Adds readme files for all current components
- Adds a readme file for creating a new component
- Missing action information since it's not completed yet
- Updates the index readme to explain what it does
When reviewing, I recommend viewing the actual branch to see the pretty versions of the readme files.

Added readmes

---

components/activity/editor/d2l-activity-editor-availability.js
components/activity/editor/d2l-activity-editor-main-collection.js
components/activity/editor/d2l-activity-editor-type-assignment.js
components/activity/name/d2l-activity-name-learning-path.js
components/common/d2l-hm-course-image.js
framework/hypermedia-lit-mixin.js
helper/deepCopy.js
state/HypermediaState.js
state/sirenComponents/SirenLink.js
state/sirenComponents/SirenSubEntity.js
state/store.js

SelflessEntities they work!

---

README.md
creating-new-components.md

* name changes
* actions
* route

Add actions and route information to readmes

---

components/activity/image/d2l-activity-image-course.js
components/activity/item/d2l-activity-item.js
package.json

Use accumulator mixin

---

.travis.yml

[US121663](https://rally1.rallydev.com/#/detail/userstory/448519079572?fdp=true)
Use Node 12 because BSI uses 12

Change travis to use node 12

---

components/activity/editor/collection/d2l-activity-editor-main-collection.js
components/activity/editor/d2l-activity-editor-footer.js
components/activity/editor/d2l-activity-editor-header.js
components/activity/editor/d2l-hc-activity-editor.js
components/activity/name/d2l-activity-name-editor.js

feat: Fix up learning path view.

---

components/activity/description/d2l-activity-description-editor.js
components/activity/editor/collection/d2l-activity-editor-main-collection.js
components/activity/editor/d2l-activity-editor-footer.js
components/activity/image/custom/d2l-activity-image-course.js
components/activity/image/d2l-activity-image.js
components/activity/list/d2l-activity-list-item.js
components/activity/name/custom/d2l-activity-name-course.js
components/activity/name/d2l-activity-name-editor.js
components/activity/name/d2l-activity-name.js
components/activity/type/d2l-activity-type.js
components/common/d2l-hc-course-image.js
components/common/d2l-hc-name.js
components/common/lang/en.js
components/common/lang/localization.js
foundation-components.serge.json

Yup it works!
There might be a problem with subentities which will be an engine problem but good for now!

feat: Skeletons!

---

components/activity/editor/collection/d2l-activity-editor-main-collection.js

[US122856](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F459739288064&fdp=true?fdp=true)
It works y'all!
- Save button will save the state
- Cancel button will not save the state
- woopwoop
- manual testing on `polarisdev`
- Tested adding activities and saving
- Tested reordering activities
- Tested deleting activities

feat: Connect the new bulk activity route to the component

---

components/activity/description/d2l-activity-description-editor.js
components/activity/description/lang/en.js
components/activity/editor/assignment/d2l-activity-editor-main-assignment.js
components/activity/editor/collection/d2l-activity-editor-collection-add.js
components/activity/editor/collection/d2l-activity-editor-main-collection.js
components/activity/editor/collection/lang/en.js
components/activity/editor/d2l-activity-editor-footer.js
components/activity/editor/lang/en.js
components/activity/name/custom/d2l-activity-name-learning-path.js
components/activity/name/d2l-activity-name-editor.js
components/activity/name/lang/en.js
components/activity/type/assignment/d2l-activity-type-editor-assignment.js
components/activity/type/d2l-activity-type.js
components/activity/type/lang/en.js

Context:
To work with bsi, we can't have '.' in lang term labels.

Fixing lang term labels

---

components/activity/editor/collection/d2l-activity-editor-main-collection.js
components/activity/editor/lang/en.js

Tested on local.
Spacing is a bit off. Will need my UI tweaks PR to be merged and this on merged before fixing that.
Says: Click Add Activities to get started now.

Feat: No activities and Skeletons on list

---

components/activity/dialog/d2l-activity-dialog-load-failed.js
components/activity/dialog/lang/localization.js
components/activity/dialog/lang/localize-dialog.js

Merged new component but it conflicted with lang file changes.

fix: Broken langs for dialog

---

components/activity/type/d2l-activity-type.js

Context:
Localization for labels was missed.
[US124010](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F483548927728)

Add localization to activity types

---

components/activity/editor/collection/d2l-activity-editor-main-collection.js
components/activity/editor/lang/en.js

Added languaged for activity count

fix: Style fixes for activity

---

components/activity/description/d2l-activity-description-editor.js
components/activity/editor/collection/d2l-activity-editor-collection-add.js

Fixes overlapping issues for DE42161 and DE42162
Tested on Chrome And Firefox. 
Todo: test on Mac Safari after merge to master ( safari blocks http://localhost:8080 for security reasons)

fix: defects DE42161, DE42162

---

components/activity/editor/collection/d2l-activity-editor-main-collection.js
components/activity/editor/d2l-hc-activity-editor.js

[DE42123](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F485899322752)
When dragging a list item to the top or bottom, the screen does not scroll.
Discussed design of added scrollbar with Abbie. Will look into a nicer scrollbar like what assignments uses.
Tested on polarislocalbsi in chrome.

fix: reduces content size and adds scroll bar

---

components/activity/editor/d2l-activity-editor-footer.js
components/common/d2l-activity-visibility.js

Made it so the visibility toggle won't flicker.

fix: Made it so the visibility toggle won't flicker.

---

components/activity/description/d2l-activity-description-editor.js

Can't use the lovely core component yet :(

Description has new lines!

---

components/activity/editor/collection/custom/quiz/d2l-activity-list-item-question.js

To reflect the api change done by @alexli01 recently.

fix: question property change

---

components/activity/description/test/d2l-activity-description-editor.test.js
components/activity/description/test/d2l-activity-description.test.js
components/activity/editor/test/d2l-activity-editor.test.js
components/activity/name/test/d2l-activity-name-editor.test.js
components/activity/name/test/d2l-activity-name.test.js
karma.conf.js
karma.sauce.conf.js

We want tests to be in component directories. This pr is moving the tests we currently have.

test: reorganize tests to be in component directory

---

components/activity/code/custom/d2l-activity-code-editor-learning-path.js
components/activity/code/custom/lang/en.js
components/activity/code/d2l-activity-code-editor.js
components/activity/code/lang/en.js

fix dynamic imports
imports are limited to the current folder

fix: dynamic imports must be relative to current folder

---

components/activity/code/custom/d2l-activity-code-editor-learning-path.js
components/activity/code/custom/lang/en.js
components/activity/code/d2l-activity-code-editor.js
components/activity/code/lang/ar.js
components/activity/code/lang/cy-gb.js
components/activity/code/lang/da-dk.js
components/activity/code/lang/de.js
components/activity/code/lang/en.js
components/activity/code/lang/es-es.js
components/activity/code/lang/es.js
components/activity/code/lang/fr-fr.js
components/activity/code/lang/fr.js
components/activity/code/lang/ja.js
components/activity/code/lang/ko.js
components/activity/code/lang/localization.js
components/activity/code/lang/nl.js
components/activity/code/lang/pt.js
components/activity/code/lang/sv.js
components/activity/code/lang/tr.js
components/activity/code/lang/zh-tw.js
components/activity/code/lang/zh.js

I don't understand why dynamic imports wants to break anything, so I am reverting back to the static localization until we can look into the issue more

revert to static localization

---

features/discover/test/d2l-discover-rule-picker-dialog.test.js
karma.sauce.conf.js

I expect at least one thing to break.

test: Adding features to sauce config

---

components/activity/editor/d2l-activity-editor-footer.js

Basically, updated the tab order so visibility toggle first in the tab order for the footer.

Tab order change for footer.

---

components/activity/description/d2l-activity-description-editor.js
components/activity/description/test/d2l-activity-description-editor.test.js
components/activity/editor/collection/d2l-activity-editor-main-collection.js
components/activity/editor/d2l-activity-editor-footer.js
components/activity/editor/d2l-activity-editor-header.js
components/activity/editor/d2l-hc-activity-editor.js
demo/data/base/new-learning-path.json

Fix the css!

---

components/activity/editor/collection/custom/quiz/d2l-activity-collection-editor-quiz.js
components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js
components/activity/list/custom/quiz/d2l-activity-list-item-question.js

- to wire up open fullscreen dialog method on item click
- to refresh item and collection when return from edit

feat: open edit question fullscreen dialog

---

components/activity/editor/collection/custom/quiz/d2l-activity-collection-editor-quiz.js
components/activity/list/custom/quiz/d2l-activity-list-item-section.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F496660506452%2Ftasks&fdp=true?fdp=true

feat: Ali/us124813: display section content including nested content

---

features/workToDo/d2l-w2d-work-to-do.js
features/workToDo/demo/d2l-w2d-work-to-do.html
features/workToDo/demo/data/worktodo.json
features/workToDo/test/.eslintrc.json
features/workToDo/test/d2l-w2d-work-to-do.test.js
index.html

Basically a simple component that prints out the entity given to it by the href.

work to do base

---

components/activity/editor/collection/d2l-activity-card-learning-path.js
components/activity/editor/lang/en.js
foundation-components.serge.json

The localization information needs to be added to serge.

fix: adding learning path code specific translations to serge

---

features/discover/README.md

Updating component name from `d2l-discover-entitlement-rules` to `d2l-discover-rules`

docs: Update README.md

---

features/workToDo/d2l-w2d-list.js
features/workToDo/d2l-w2d-work-to-do.js
features/workToDo/demo/data/overdue.json
features/workToDo/demo/data/two-weeks.json
features/workToDo/demo/data/user.json
features/workToDo/demo/data/year.json
features/workToDo/w2dDateCategoryObserver.js
package.json

Make the parent list.
Basically categorizes what we are getting from the API and list what we are doing.

feat: Show categories and their items.

---

features/workToDo/d2l-w2d-empty-state-image.js
features/workToDo/d2l-w2d-no-activities.js
features/workToDo/demo/d2l-w2d-no-activities.html
features/workToDo/lang/en.js
index.html

[US126209](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F514448373588&fdp=true?fdp=true)
This pr is adding the basics of the component for when there are no upcoming/overdue activities.

feat: work to do no activities component

---

features/workToDo/lang/en.js

[US126802](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F519576413652&fdp=true?fdp=true)
There are some minor differences between design language and what we have.
Reviewed differences with Abbie to ensure correct terms are used.

fix: update terms to match design

---

components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js
components/activity/list/custom/quiz/d2l-activity-list-item-question.js
components/activity/list/custom/quiz/d2l-activity-list-item-questionpool.js
components/activity/list/custom/quiz/d2l-activity-list-item-section.js
components/activity/list/custom/quiz/lang/en.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F511783502328&fdp=true?fdp=true

feat: Ali/us126035: display question pools in quiz collection

---

components/activity/list/custom/quiz/d2l-activity-list-item-questionpool.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F519089689960&fdp=true?fdp=true

Ali/us126690: refresh question pool after edit.

---

features/workToDo/d2l-w2d-attribute-list.js
features/workToDo/d2l-w2d-list-item.js
features/workToDo/d2l-w2d-list.js
features/workToDo/d2l-w2d-work-to-do.js
features/workToDo/lang/en.js
features/workToDo/w2dDateCategoryObserver.js

feat: Style Work to Do

---

components/activity/icon/d2l-activity-icon.js
features/workToDo/d2l-w2d-collections.js
features/workToDo/d2l-w2d-list-item.js
features/workToDo/d2l-w2d-list.js
features/workToDo/d2l-w2d-work-to-do.js
features/workToDo/lang/en-us.js
features/workToDo/w2dDateCategoryObserver.js
features/workToDo/w2dSummonActionObserver.js

Add work to do to organization.
Require some fixes on how things are done to prevent some issues.
limit the widget to only show 6 course.
Make the back link work.

fix: Allow work to do to work with organizations

---

package.json

"d2l-navigation": "BrightspaceUI/navigation#semver:^4",

Import d2l-navigation

---

components/activity/description/custom/DescriptionMixin.js
components/activity/description/custom/d2l-activity-description-course.js
components/activity/description/custom/d2l-activity-description-survey.js
components/activity/description/d2l-activity-description.js
components/activity/icon/d2l-activity-icon.js
components/activity/name/custom/d2l-activity-name-course.js
components/activity/name/custom/d2l-activity-name-survey.js
components/activity/name/d2l-activity-name.js
components/activity/type/d2l-activity-type.js
components/common/d2l-hc-name.js
features/workToDo/d2l-w2d-attribute-list.js
features/workToDo/d2l-w2d-collections.js
features/workToDo/d2l-w2d-list-item.js
features/workToDo/d2l-w2d-list.js
features/workToDo/d2l-w2d-no-activities.js
features/workToDo/d2l-w2d-work-to-do.js
features/workToDo/w2dDateCategoryObserver.js
features/workToDo/w2dSummonActionObserver.js

Use overdue action
Fixed course
Fixed Survey
Added no activity view

feat: overdue action + some defect fixes.

---

components/activity/list/custom/quiz/d2l-activity-list-item-questionpool.js

removed extra checkbox from question pool list item

fix: remove extra checkbox from question pool

---

features/workToDo/d2l-w2d-work-to-do.js
features/workToDo/lang/en.js

fix: Update Nav for work to do

---

features/workToDo/w2dSummonActionObserver.js

fix: Update to set fields.

---

features/workToDo/d2l-w2d-list-item.js

fix: Start Date

---

features/workToDo/d2l-w2d-attribute-list.js
features/workToDo/d2l-w2d-collections.js
features/workToDo/w2dSummonActionObserver.js
package.json

Paging for the fullscreen mode.

feat: Work to Do Paging

---

features/workToDo/lang/cy-gb.js
features/workToDo/lang/fr.js
features/workToDo/lang/tr.js

Updating Translations 2105 28/04/2021
translations included single quote chars and were breaking strings

Fix escaping in lang files

---

features/workToDo/lang/fr-on.js

need to update w2d translations

fix: w2d update fr-on with recent translations

---

features/workToDo/d2l-w2d-attribute-list.js

[DE43241](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F600431718008&fdp=true?fdp=true)
No more dot in the skeleton.

fix: Removing dot from skeleton

---

features/workToDo/d2l-w2d-collections.js
features/workToDo/d2l-w2d-work-to-do.js
features/workToDo/w2dDateCategoryObserver.js

This will limit overdue activities in work to do by the configuration limit.

fix: Limit overdue to the config var

---

features/workToDo/d2l-w2d-attribute-list.js
features/workToDo/d2l-w2d-list-item.js

Bullets don't show up in fullscreen and only fullscreen so this is probably the fix.
https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F601797704532

fix: safari bullets not showing up

---

features/workToDo/d2l-w2d-collections.js

Currently, the total number of pages may appear to be zero. This makes it so that the number can't be below 1.

fix: W2d total pages minimum of 1

---

components/activity/list/custom/quiz/lang/fr-on.js
components/activity/type/lang/fr-on.js
features/discover/lang/fr-on.js
foundation-components.serge.json

Some Ontario French translations were missing for work to do. Went through the repo to check the translations are present everywhere.

fix: add ontario french where needed

---

components/activity/description/test/d2l-activity-description-editor.test.js
features/workToDo/d2l-w2d-collections.js
features/workToDo/d2l-w2d-list-item.js
features/workToDo/d2l-w2d-list.js
features/workToDo/d2l-w2d-work-to-do.js
features/workToDo/w2dDateCategoryObserver.js
features/workToDo/w2dSummonActionObserver.js

Changes to load the work to do widget. First page only.

Loading the work to do widget

---

features/workToDo/d2l-w2d-collections.js
features/workToDo/w2dDateCategoryObserver.js
features/workToDo/w2dSummonActionObserver.js

load 1 then 2 then 1 then 2 for pages works!

fix: Update so numbers and ordered

---

features/discover/demo/discover-api.js
features/discover/demo/discover-api.mjs
web-dev-server.config.mjs

I ran into an issue with @BhamelinD2L 's change to `web-dev-server` that prevented me from running demos. I fixed it.
`rm -rf node_modules`
`rm package-lock.json`
`npm install`
`npm start`
Works now instead of erroring.

fix: Fix commonjs import

---

components/activity/type/lang/fr-on.js

Changed Travail to Tache

---

README.md
examples/d2l-hmc-actions.js
examples/d2l-hmc-example.js
examples/d2l-hmc-properties.js
examples/d2l-hmc-routing.js
examples/demo/actions.json
examples/demo/d2l-hmc-examples.html
examples/demo/name.json
examples/demo/routing.json
index.html

```Context```
Adding some example components for basic interactions with foundations-engine. Hoping to establish an area that can be used for learning foundations without having to create a new component from scratch.
is there any other interactions or known pitfalls that would be good to cover?

Adding example components

---

features/workToDo/d2l-w2d-attribute-list.js
features/workToDo/d2l-w2d-list-item.js

* Remove Flex. Add truncation.
* Actually add truncation.
* Fix start spacing.
* Fix extra whitespace.
Adding this will force no whitespace.
* Removing unnecessary css.
I hope I don't regret this.
* Move wrapping div to parent function.
Wraps the extra start date chip.
* Fix bullet margins.
Thank you max.
Co-Authored-By: Max <57962078+mbardakovD2L@users.noreply.github.com>
* Put the whitespace back in.
For even spacing around bullet.
* Restore original margin spacing
Co-Authored-By: Max <57962078+mbardakovD2L@users.noreply.github.com>
Co-authored-by: Max <57962078+mbardakovD2L@users.noreply.github.com>

fix: DE44196 Fix due date being cut off (#272)

---

features/workToDo/d2l-w2d-collections.js

Rally: [DE44396](https://rally1.rallydev.com/#/357251704080ud/iterationstatus?detail=%2Fdefect%2F603983938391&fdp=true?fdp=true)

DE44396: View All Work not loading for some users

---

features/workToDo/d2l-w2d-collections.js
features/workToDo/w2dDateCategoryObserver.js

https://rally1.rallydev.com/#/357251704080ud/iterationstatus?detail=%2Fdefect%2F603778332755
https://rally1.rallydev.com/#/357251704080ud/iterationstatus?detail=%2Fdefect%2F603983938391
We want these fixes in 20.21.7 as well.

Backport DE44343 and DE44396

---

features/workToDo/d2l-w2d-collections.js
features/workToDo/w2dDateCategoryObserver.js

https://rally1.rallydev.com/#/357251704080ud/iterationstatus?detail=%2Fdefect%2F603778332755
https://rally1.rallydev.com/#/357251704080ud/iterationstatus?detail=%2Fdefect%2F603983938391
Needs to be in 20.21.8

fix: backport DE44343 and DE44396

---

components/activity/editor/collection/custom/quiz/d2l-activity-collection-editor-quiz.js
components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js
components/activity/list/custom/quiz/d2l-activity-list-item-question.js
components/activity/list/custom/quiz/d2l-activity-list-item-section.js

https://rally1.rallydev.com/#/?detail=/userstory/606032653532&fdp=true

fix: US128512: refresh section after objects are imported.

---

features/workToDo/d2l-w2d-telemetry.js

https://rally1.rallydev.com/#/357251704080/detail/userstory/607987877113

Force absolute URLs in telemetry events

---

features/lti/d2l-lti-activity.js
features/lti/test/d2l-lti-activity.test.js

Embedded mode - `External Activity`
Collapsed mode - Tile + description

feat: US131095 - display the name (if available) and description on the LTI card
