BrightspaceHypermediaComponents/foundation-components

components/activity-collection/editor/d2l-activity-collection-editor-lp.js, components/activity/editor/d2l-acitivity-editor-main-lp.js, components/activity/editor/d2l-activity-editor-header.js, components/activity/editor/d2l-activity-editor.js, framework/hypermedia-components.js, framework/hypermedia-lit-mixin.js, state/HypermediaState.js, state/sirenComponents/Common.js, state/sirenComponents/SirenClasses.js, state/sirenComponents/SirenEntity.js, state/sirenComponents/SirenLink.js, state/sirenComponents/SirenProperty.js, state/sirenComponents/SirenSubEntities.js, state/sirenComponents/SirenSubEntity.js, state/sirenComponents/sirenComponentFactory.js, state/store.js
This basically gives us the ability to pull a list of sub entities.
Each one is the different course items for the learning path. Once I get my split mixin for list items in we can add a course list.
Also, fixed some other issues. 
- Fixes #9 
- Fixes #10
- Fixes #11
I also added the ability to add `method` to give us more options. I ended up not needing this change yet after talking to Eric. But could be super useful. I would want the method to also send the raw siren object for more options but lets do that if we need it.
=> Sub Entities. Yes please!

README.md, components/activity-collection/editor/d2l-activity-collection-editor-lp.js, components/activity/description/d2l-activity-description-course.js, components/activity/description/d2l-activity-description-learning-path.js, components/activity/editor/d2l-activity-editor-availability.js, components/activity/editor/d2l-activity-editor-footer.js, components/activity/editor/d2l-activity-editor-header.js, components/activity/editor/d2l-activity-editor-main-assignment.js, components/activity/editor/d2l-activity-editor-main-collection.js, components/activity/editor/d2l-activity-editor-name.js, components/activity/editor/d2l-activity-editor-score.js, components/activity/editor/d2l-activity-editor-sidebar-assignment.js, components/activity/editor/d2l-activity-editor-submission.js, components/activity/editor/d2l-activity-editor-type-assignment.js, components/activity/editor/d2l-activity-editor.js, components/activity/icon/d2l-activity-icon.js, components/activity/image/d2l-activity-image-collection.js, components/activity/image/d2l-activity-image-course.js, components/activity/item/d2l-activity-item.js, components/activity/name/d2l-activity-name-course.js, components/activity/name/d2l-activity-name-learning-path.js, components/activity/type/d2l-activity-type.js, components/common/d2l-hm-course-image.js, components/common/d2l-hm-description.js, components/common/d2l-hm-name.js, creating-new-components.md
- Names are finalized - `foundation-engine` has become `@brightspace-hmc/foundation-engine`
- Should fix the broken build
- We should add semantic versioning to `foundation-engine` as a side note to make major changes like this easier. I did this the dumb way.
=> Updating package name of foundation-engine

demo/d2l-activity-editor.html
I noticed that the demo did not appear to be loading the activity editor, determined it was due to a path error. This should fix it up.
=> Fixing demo path to d2l-activity-editor.js file

package.json
Hoping this typo is the cause of [this release error](https://github.com/BrightspaceHypermediaComponents/foundation-components/runs/1475977329).
=> Fix typo in repo url for github actions release

.eslintrc.json, .gitignore, karma.conf.js, package.json
[US121576](https://rally1.rallydev.com/#/detail/userstory/447027030140?fdp=true)
We have basically nonexistent coverage right now, but that's fine! Now we can look at it in all of its ugly glory!!!1
Related to https://github.com/BrightspaceHypermediaComponents/foundation-engine/pull/26
=> test: Add testing coverage

components/activity/editor/collection/d2l-activity-editor-main-collection.js, creating-new-components.md
[US122956](https://rally1.rallydev.com/#/detail/userstory/460074259704?fdp=true)
Hooks up the `d2l-activity-editor-main-collection` component to support the new `subEntities` change. Other `subEntities` and `subEntity` types use routing for existing components, and the change does not affect them.
=> feat: updating collection editor to use sub entity objects

.github/workflows/ci.yml, components/activity/description/README.md, components/activity/description/d2l-activity-description-editor.js, components/activity/editor/d2l-activity-editor-header.js, karma.conf.js, karma.sauce.conf.js, package.json, test/activity/description/d2l-activity-description-editor.test.js, test/activity/description/d2l-activity-description.test.js, test/data.js, test/fetchMocks.js
```Context```
https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F378718811140
Created d2l-activity-description-editor component which adds a textarea that can be save / cancelled. Clicking save updates the description, while cancelling reverts it back to the previous state.
```Quality```
manual testing to ensure cancel / save works as expected 
Textarea should also appear larger when on smaller screens as per images in the rally story.
=> Add activity description editor component

package.json
There aren't any visual-diff tests in this repo yet so I'm removing the commands and dependencies from `package.json` (which I'm doing to all visual-diff repos anyways).  Then when tests are added we can add the workflow and readme updates.
=> ci: Remove visual-diff for now

components/activity/editor/d2l-activity-editor-footer.js
[US123696](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F478919016876)
```Context```
Cancel button should redirect to the learning paths admin page. The link to the redirect page should be added the hypermedia response with the rel "up".
```Quality```
tested with local LMS (the lms code has not been merged yet) with BSI. When clicking cancel the window is redirected to d2l/le/learningpaths/admin/view
using polarisdev (no up link in links), clicking cancel does not redirect and no errors are present in the console. This is expected behavior
*Holding off on unit tests until localizationMixin issue is resolved
=> feat: cancel LP redirects to admin view

components/activity/editor/d2l-activity-editor-footer.js, components/activity/editor/lang/en.js
Context:
[US123433](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F466974478716)
When saving a learning path fails, we give the user a dialog box asking them to attempt to save again.
Quality:
Testing using polarisdev sitelord.
- tested by throwing explicitly from the try statement
- need to test push actually throwing
=> feat: dialog box when saving an existing learning path fails

components/activity/editor/d2l-activity-editor-footer.js, components/activity/editor/lang/en.js
Context:
[US123434](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F466974498476)
We want text that is different for saving failing on a new learning path.
Quality:
Tested on polarisdev2.
- new text shows up when learning path is new
- editing text shows up when learning path is old
=> feat: dialog box for save failing on a new learning path

components/activity/dialog/README.md, components/activity/dialog/d2l-activity-dialog-load-failed.js, components/activity/dialog/lang/en.js, components/activity/dialog/lang/localize-dialog.js, components/activity/editor/d2l-hc-activity-editor.js
[US123433](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F466974478716&fdp=true&fdp=true&fdp=true?fdp=true)
First portion of story. 
- Creates a new component for displaying a dialog when an activity load fails.
- Added to the `d2l-hc-activity-editor`
- Component is generic and will intelligently display langs based on the classes
- Supports generic `activity-usage` and `learning-path`
- Cancel just closes the dialog currently - will add redirecting in a different PR
- Manual testing by forcing the engine to throw an error
- There's a problem with the engine that's not catching errors correctly but is separate from this story
=> feat: Dialog component for load failures

components/activity/editor/d2l-activity-editor-footer.js
Context:
Reset is breaking. Specifically, the href is missing in the state. We don't really need to reset so we're not going to.
=> fix: do not reset on cancel

components/activity/description/d2l-activity-description-editor.js
Basically, the description box now auto grows up to 5 lines big. The default size is now the same size as the input name box! Woot!
=> Feat: Description Auto grows to 5 lines.

components/activity/editor/collection/d2l-activity-editor-main-collection.js
**Before:** Open a learning path. Add more than one courses. Reorder courses. Add additional course(s).
Expected: courses that have been moved before second add to remain where they were in the list.
Actual: courses that have been moved are returned to the position they were added to.
**After:** State is updated when a user reorders items, so things maintain consistency.
Tested with `polarisdev2` and local BSI
=> fix: Change the state when items are reordered

components/activity/editor/d2l-activity-editor-footer.js
Context:
[US42099](https://rally1.rallydev.com/#/357252966636ud/custom/367300408400?detail=%2Fdefect%2F485856032632)
The shim was not appearing while saving, only when an error dialog appeared.
Quality:
Tested on polarislocalbsi.
https://user-images.githubusercontent.com/69812595/104953433-66395f80-5994-11eb-9991-335ebfdfe806.mp4
=> fix: shim appears when learning path is being saved

components/activity/editor/d2l-activity-editor-footer.js, components/activity/editor/lang/en.js
[DE42111](https://rally1.rallydev.com/#/357252966636ud/custom/367300408400?detail=%2Fdefect%2F485887163996)
The footer was not being resized to fit a mobile display.
Discussed how to address with Abbie. Decided we would reduce "Save and close" to "Save" on mobile displays like assignments does.
Tested on polarislocalbsi
https://user-images.githubusercontent.com/69812595/104960150-ace18680-59a1-11eb-8f77-757ccb4b9d79.mp4
=> fix: footer correctly displayed in mobile mode

components/activity/list/d2l-activity-list-item-accumulator.js
###Context:
[DE42122](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F485896470472)
Currently, using remove during keyboard mode does not remove the item from the list.
The solution here adds an action for keydown on the item. This is kind of clunky and ideally the list-item-accummulator-mixin would handle this in the future.
Tested on polarislocalbsi.
https://user-images.githubusercontent.com/69812595/105064561-f043ff80-5a4a-11eb-9062-fb26119c7853.mp4
=> fix: remove during keyboard mode removes course

components/activity/editor/collection/d2l-activity-editor-collection-add.js
Changes: 
keep track of selected activities in map object.
Notes: changes are not compatible with IE browsers (Map and Array.fom are not supported)
Testing:
manual testing for radom combination of (select, unselect, filter, load more)
ToDo: 
More testing on Firefox, Safari, new MS Edge,
=> fix defect DE42064

components/activity/name/d2l-activity-name-editor.js
[DE42104](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F485864994084l)
[DE42101](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F485859664416)
When saving, leading and trailing whitespace are currently both saved. Also, a learning path with an empty name can be saved.
This solution trims the whitespace while text is being entered.
For saving with an empty name, if the name is deleted, the learning path will save with the non-empty name it had. If the entire name was selected and deleted at once, the name is unchanged. If the name was deleted one character at a time, the last character deleted is saved as the name.
Tested on polarislocalbsi.
=> fix: prevents saving empty name

components/activity/editor/d2l-activity-editor-footer.js
Fixes Bug 6 caught by @AKobets 
**Before:** 6) Console logs exception when clicking Save And Close button
```
Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'DocumentFragment': '##save-buttons' is not a valid selector.
at HTMLElement.updated (https://s.brightspace.com/lib/bsi/20.21.2-102/unbundled/backdrop.js:1:2147)
at HTMLElement.performUpdate (https://s.brightspace.com/lib/bsi/20.21.2-102/unbundled/lit-element.js:1:16932)
at HTMLElement._enqueueUpdate (https://s.brightspace.com/lib/bsi/20.21.2-102/unbundled/lit-element.js:1:16421)
```
(Error will be printed and then disappears. Enable 'preserve log upon navigation' in Dev tools Settings)
**After:** No bug because we're not sending a bad `id`
Tested on `polarisdev2` with local BSI
=> fix: Remove extra hashtag

components/activity/editor/d2l-activity-editor-footer.js, components/activity/editor/d2l-hc-activity-editor.js
[DE42228](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F486927762512)
In firefox, the save and close, cancel, and visibility are appearing in front of the shim from the collection dialog.
Tested on polarislocalbsi in chrome and firefox.
=> fix: footer appears behind browse library dialog

components/activity/editor/collection/d2l-activity-editor-collection-add.js, components/activity/editor/collection/lang/en.js
[DE42126](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F485904871028)
```Context```
The load more button would get stuck as a spinner when a network failure occurred. I've added a try/catch around the call to display an error message when this happens and release the isLoadingMore flag. 
```Quality```
Manual testing using polarisLocalBSI
1) load the page
2) in dev tools, set network connection to offline
3) clicking load more will cause the button to revert back to a button and error message is shown
4) in dev tools, set network connection to online
5) click load more, new activities are loaded and error is removed
=> fix: show load more error under button

components/activity/editor/collection/d2l-activity-editor-collection-add.js, components/common/lang/en.js
[DE42282](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F489328036512)
```Context```
Clicking the load more button would trigger the screen reader to read each new activity name as they were loaded. Skeleton items were also being read as "name". This caused some spam.
The dialog was created as an aria-live region that will announce changes, so I've removed the attribute. 
```Quality```
Tested using NVDA screen reader
1) Clicking load more no longer causes activities to be announced
2) Tabbing through the new activities will continue to announce the name as they receive focus
=> fix: Removed aria-live to prevent SR reading changes

components/activity/list/d2l-activity-list-item-accumulator.js, components/activity/list/lang/ar.js, components/activity/list/lang/de.js, components/activity/list/lang/en.js, components/activity/list/lang/es.js, components/activity/list/lang/fr.js, components/activity/list/lang/ja.js, components/activity/list/lang/ko.js, components/activity/list/lang/localization.js, components/activity/list/lang/nl.js, components/activity/list/lang/pt.js, components/activity/list/lang/sv.js, components/activity/list/lang/tr.js, components/activity/list/lang/zh-tw.js, components/activity/list/lang/zh.js, foundation-components.serge.json
[DE42167](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F486263074800)
The remove word is not localized in the context menu for list items.
Tested in polarislocalbsi.
- tested English: 'Remove' was shown
- tested French: 'Supprimer' was shown
=> fix: Ten/localize list remove

test/activity/description/d2l-activity-description-editor.test.js, test/data.js, test/fetchMocks.js
[US124632](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F492478321928)
When we went to localize components, the tests stopped working when using the Hypermedia Mixin and Localize Mixin together. Something Maya did fixed this issue but the tests were not updated. Thus, this pr is updating the tests to match the updated from Maya.
Tested locally.
=> fix: update description tests

components/activity/editor/d2l-activity-editor-footer.js, components/common/d2l-hc-visibility-editor.js
While looking into creating demos, I noticed the `activity-visibility-editor` is a misnomer, as entities could have visibility without being activities.
- Tested with local bsi and learning paths
=> refactor: Change name of visibility editor

components/activity/editor/d2l-hc-activity-editor.js, features/assignments/d2l-activity-editor-submission.js
[US122674](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F458814721568)
The learning path editor needs to be switched to use primary-secondary to accommodate additional information. This pr is updating the editor to use the template but does not use the secondary area yet.
Some CSS formatting still needs to be done.
- tested locally in sitelord with local bsi
=> feat: activity editor defaults to primary-secondary template

README.md, features/discover/README.md, features/discover/d2l-discover-entitlement-rules.js, features/discover/demo/condition-typea-values.json, features/discover/demo/condition-typeb-values.json, features/discover/demo/condition-types.json, features/discover/demo/course-entitlement-rules.json, features/discover/demo/course.json, features/discover/demo/d2l-discover-entitlement-rules.html, features/discover/demo/matching-users.json, features/discover/lang/en.js, features/discover/lang/localization.js, index.html, package.json
[US123170](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fuserstory%2F462626337568&fdp=true?fdp=true)
The first of what will likely be several small-ish PRs to bring the new Discover entitlement components into the fold.
- Adds the `d2l-discover-entitlement-rules` component
- Brings together two UI components: the checkbox drawer and the rule-picker
- Adds a demo that includes mock data showing what the API should look like
- Run `npm start` and visit the demo page to manually test
- The `rule-picker-dialog` and `rule-picker` components will be migrated to `Foundations` because they are heavily data-oriented.
=> feat: Added the discover component and demo

components/activity/editor/collection/d2l-activity-card-learning-path.js, components/activity/editor/collection/d2l-activity-editor-secondary-card.js, components/activity/editor/collection/d2l-activity-editor-sidebar-collection.js, components/activity/editor/collection/d2l-activity-editor-sidebar-learning-path.js, components/activity/editor/d2l-activity-editor-sidebar.js
[US122674](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F458814721568&fdp=true?fdp=true)
We're adding the secondary pane for the org code. This is creating a ui component for the cards we will use and implementing a hypermedia component for the card.
Tested with local bsi in sitelord.
=> feat: add secondary slot ui card and use it for learning path

components/activity/editor/collection/d2l-activity-editor-sidebar-learning-path.js, demo/data/base/add-existing-activity.json, demo/data/base/collection-full.json, demo/data/base/existing-learning-path.json, demo/editor/d2l-activity-editor-footer.html, demo/editor/d2l-activity-editor-header.html, demo/editor/d2l-activity-editor-main.html, demo/editor/d2l-activity-editor-sidebar.html, index.html
[US122506](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F457719949704&fdp=true?fdp=true)
We have a bunch of components for collection editor. We want to show them off individually in demo pages.
Tests demo pages locally.
The sidebar needs to be cleaned up
=> doc: adding demo pages for collection editor components

components/activity/code/d2l-activity-code-editor.js
```Context```
generic code component was missed when updating back to dynamic localization
```Quality```
tests still passing
manual testing using demos
remembered fix: in PR name
=> fix: missed updating localiazation for code

features/discover/d2l-discover-sample-button.js, features/discover/demo/d2l-discover-rules.html
[US123769](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fuserstory%2F480099321508&fdp=true&fdp=true?fdp=true)
Attempting to include a bare basic webcomponent in a legacy page via the "double adaptor" strategy @BhamelinD2L has talked about. See story for details.
Added to demo page but tests unnecessary since this is a temporary component. `fix` prefix is to make sure we bump the version.
=> fix: Add sample button for legacy page test

components/activity/code/custom/d2l-activity-code-editor-learning-path.js
https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F459180378604
```Context```
Screen reader was not matching expectation in test docs
```Quality```
screen reader should read textfield {label} {description} {value}
tested using NVDA
=> fix: add aria-label to code input

demo/data/base/new-learning-path.json
```Context```
Organization and specialization rels were removed from the new learning path json, this caused the editor demo to not load properly. 
```Quality```
Editor demo now populates the properties
=> fix: demo data for editor

components/activity/editor/collection/d2l-activity-card-learning-path.js
The name was updated in ui-labs repo, so we need to update it here.
=> fix: rename secondary-card to caketray

components/activity/code/custom/d2l-activity-code-editor-learning-path.js, components/activity/code/test/d2l-activity-code-editor.test.js
```Context```
Code component was missing tests for adding an empty string. I've added the test for the default editor, but the same test for learning path custom version breaks sinon spy. The spy is throwing an error due to the commit() call not having arguments, which is necessary for the functionality to work. 
Moved the d2l-activity-code-editor-learning-path tests to their own block, so a lot of the code is just being moved around. The new block needed the addMock calls. 
```Quality```
adding unit tests
=> fix: added empty string test for codes

README.md, creating-new-components.md
Currently it's hard to find the observables info for component creation. This is adding links to relevant documentation locations to make it easier to find when needed.
=> doc: add engine link for observables to documentation

features/discover/d2l-discover-rule-picker-dialog.js, features/discover/d2l-discover-rule-picker.js, features/discover/d2l-discover-rules.js, features/discover/test/d2l-discover-rule-picker-dialog.test.js
[US123170](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fuserstory%2F462626337568&fdp=true?fdp=true)
The rule picker dialog should remove changes from the dialog if cancel is pressed.
I could have sworn I had this working before. Anyway, it is fixed now.
=> fix: Fixing rule picker cancel

components/activity/editor/d2l-activity-editor-footer.js
[US124081](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F483748245128)
```Context```
Learning paths will be display save toasts after the redirect. To support this I've added links to the hypermedia response with a rel of up and either "save" or "cancel". When the footer detects either of these rels it is given preference when performing those actions. If it does not detect them, then any "up" rel is used.
```Quality```
Manual test using local LMS changes
- When save and cancel rels are present, they are respected
- When only one is present, then the up rel is used for the other action
- When only a generic "up" link is given, then it is used for both
=> feat: footer support for save and cancel links 

components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js
Dispatching `update-total-quiz-points` event from `d2l-activity-collection-item-quiz`. This event is caught and handled in `d2l-activity-quiz-editor` in the `activities` repo.
**Related PRs:**
`siren-sdk`: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/301
`activities`: https://github.com/BrightspaceHypermediaComponents/activities/pull/1624
[US126109](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F512322551332&fdp=true?fdp=true): Refresh total points on edit
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F512322551332&fdp=true?fdp=true
=> US126109 dispatched update points event after collection refreshed

features/workToDo/lang/ar.js, features/workToDo/lang/cy.js, features/workToDo/lang/da.js, features/workToDo/lang/de.js, features/workToDo/lang/en.js, features/workToDo/lang/es-es.js, features/workToDo/lang/es.js, features/workToDo/lang/fr-fr.js, features/workToDo/lang/fr-on.js, features/workToDo/lang/fr.js, features/workToDo/lang/ja.js, features/workToDo/lang/ko.js, features/workToDo/lang/nl.js, features/workToDo/lang/pt.js, features/workToDo/lang/sv.js, features/workToDo/lang/tr.js, features/workToDo/lang/zh-cn.js, features/workToDo/lang/zh-tw.js, foundation-components.serge.json
https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F514448373588
Working on making empty widget panels. Figured we should take the old lang terms to make our lives easier.
=> feat: added work to do lang terms from activities repo

features/discover/d2l-discover-rules.js
[US120165](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fuserstory%2F424331214124&fdp=true?fdp=true)
Removing the label for Discover rules because it's less complicated than hiding the existing one in the LMS. This should also ensure more consistent spacing, plus makes this component more reusable.
- Demo page
=> fix: Removing the discover rules label

foundation-components.serge.json
[US126209](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F514448373588&fdp=true?fdp=true)
I put files in the wrong place in the serge file. 😢  This fixes that.
=> fix: fixing surge file for location of WTD lang files

components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js, components/activity/list/custom/quiz/d2l-activity-list-item-section.js
Refreshing the Section name after editing using the new `_refreshState` in `foundation-engine`.
Not to be merged until https://github.com/BrightspaceHypermediaComponents/foundation-engine/pull/91 is merged.
[US126257](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F514848992408%2Ftasks&fdp=true?fdp=true): Edit a section
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F514848992408%2Ftasks&fdp=true?fdp=true
=> US126257 refresh Section name on edit

components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js, components/activity/list/custom/quiz/d2l-activity-list-item-section.js
~~I was having a bit of a hard time verifying this in the UI with my networks speeds but I think~~ this change should force the Section name to skeletonize after QED closes so we don't have the issue of the old section name persisting for a few seconds before it gets updated.
[US126257](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F514848992408&fdp=true?fdp=true): [ui] Edit a section
=> fix: US126257 skeletonize section on QED close

components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js, components/activity/list/custom/quiz/d2l-activity-list-item-question.js, components/activity/list/custom/quiz/d2l-activity-list-item-section.js
Fix for:  "When using FACE Quiz, user cannot check the checkmark next to an existing question, section, (assume question pool too). Instead it goes into edit.  Seems like the click target is the whole row?"
Note this bug still happens for items nested within sections but the proper way to render nested lists are still a WIP.
https://trello.com/c/GKSEmBoY
=> fix quiz collection item checkbox at root level

features/discover/d2l-discover-rules.js
Jeff wants things to line up! Also adjusted the wording on the todos and made some room for things that will need to happen in the near future.
Checked for pixel perfect in Photoshop
=> fix: Adjusting margin for Discover subtle buttons

features/workToDo/d2l-w2d-collections.js, features/workToDo/d2l-w2d-list.js
On the widget collapsed view if there was more then 6 overdue, then upcoming wouldn't be limited. This is now fixed.
=> Limit is only going to be 6!

features/workToDo/d2l-w2d-list-item.js, package.json
[US127302](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F600483964584&fdp=true?fdp=true)
The start date in full screen is currently displayed in line with the description. We want it to be inline with the type of activity and course.
=> fix: move start date to the attribute list

features/discover/d2l-discover-rules.js, features/discover/test/d2l-discover-rules.test.js
[US126747](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fuserstory%2F519521658884&fdp=true?fdp=true)
- Uses the `rules` field added in the BFF: https://github.com/Brightspace/discovery-bff/pull/119
- Removes the JSON encoding from here because this is done already in the engine.
This should help make the request more consistent with other hypermedia APIs. This approach was chosen over altering the `foundation-engine` to support unnamed arrays.
- Existing unit tests
=> fix: Discovery bff integration - add rules field

features/workToDo/d2l-w2d-collections.js, features/workToDo/d2l-w2d-no-activities.js
[DE43228](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F600191816024&fdp=true?fdp=true)
Based on the state of future events, we want to display different messages to the learner. This updates the widget to display appropriate messages.
Tested locally.
=> feat: work to do message displays different empty messages

features/workToDo/d2l-w2d-collections.js
Overdue activities no longer show up with today first.
=> fix: w2d overdue order

features/workToDo/d2l-w2d-list-item.js
[DE43357](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F602042657008&fdp=true?fdp=true)
We're missing missing translating the start date of an activity.
Tested with local bsi, lms, and components.
=> fix: W2D. translate start date

features/workToDo/d2l-w2d-collections.js
[DE43416](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F602794179756&fdp=true?fdp=true)
Full screen for w2d currently displays incorrectly when there are no overdue activities for the user.
Tested locally.
=> fix: pagination handles no overdue activities

components/activity/editor/collection/custom/quiz/d2l-activity-collection-editor-quiz.js, components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-delete-quiz.js
[US126706](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F519271058560&fdp=true?fdp=true): [ui] delete questions and question pools from a root level
=> fix: disable delete btn when user missing perm

features/workToDo/d2l-w2d-collections.js
[DE43466](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F603476791780&fdp=true?fdp=true)
When collapsed, we are seeing a max of 6 upcoming activities counted in the header. We want this to reflect the total number of upcoming activities.
Tested locally.
=> fix: upcoming week activity count

features/workToDo/d2l-w2d-collections.js
The last page is not showing up if there are only overdue activities.
Solution: only subtract if there are overdue and upcoming
=> fix: w2d last page missing when only overdue activities

features/discover/d2l-discover-rules.js, features/discover/test/d2l-discover-rules.test.js
The checkbox portion of the component in the LMS is not behaving as expected because the current event it is attempting to catch, `d2l-checkbox-drawer-checked-change`, is not `composed`. Composed events are able to pierce the shadow DOM.
- Adds a new bubbling, composed event: `d2l-rules-checkbox-change`
- New unit test added
=> fix: Use composed event for discover rules

features/discover/mixins/match-count-mixin.js
With the [engine PR](https://github.com/BrightspaceHypermediaComponents/foundation-engine/pull/102) merged, this PR updates the `match-count-mixin` to use the new bypassCache argument and retrieve an uncached match count.
=> fix: Use bypassCache argument in match count summon

package.json
eslint-plugin-lit release version 1.5, which is causing syntax errors during PR linting. Downgrading to 1.4.1 for now
=> Downgrade eslint-plugin-lit to stable version

components/activity/name/custom/d2l-activity-name-assignment.js, components/activity/name/custom/d2l-activity-name-checklist.js, components/activity/name/custom/d2l-activity-name-content.js, components/activity/name/custom/d2l-activity-name-course.js, components/activity/name/custom/d2l-activity-name-discussion.js, components/activity/name/custom/d2l-activity-name-quiz.js, components/activity/name/custom/d2l-activity-name-specialization.js, components/activity/name/custom/d2l-activity-name-survey.js, components/common/d2l-hc-name.js, features/lti/d2l-lti-activity.js
This PR updates activities to extend the core `LabelMixin` so that these components can be referenced as labels for list-items and other future selectable components such as in tables. 
I initially went down the path of the factoring the contents of `d2l-hc-name` into a mixin in order to "flatten" the components and enable the `updateLabel()` call, however the Lti case is more than just a name, and in such cases it "has a" name, rather than "is a" name, so extending a name mixin doesn't make sense.
Ref: https://github.com/BrightspaceUI/core/pull/1399
=> Update activities to use the LabelMixin

components/activity/editor/collection/custom/quiz/d2l-activity-collection-editor-quiz.js
Use start-add-existing-activity and execute-multiple to add predefined list of activity usage hrefs.
Related PR in activities: https://github.com/BrightspaceHypermediaComponents/activities/pull/1836
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F601851661777
=> US129210 Add existing activity usages to quiz

features/workToDo/d2l-w2d-collections.js, features/workToDo/d2l-w2d-no-activities.js, features/workToDo/d2l-w2d-work-to-do.js
This "N weeks clear!" string will now respect the UpcomingWeekLimit config variable.
See Rally Ticket: [DE43699](https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fdefect%2F605988636084&view=aea56dea-ee73-4c07-9842-cc15d4efc0ea&fdp=true?fdp=true): 1. W2D only displays 2 weeks clear graphic despite config setting
- Main w2d component passes data from LMS
- Collections w2d component passes data to no-activities component
- Replace hardcoded value in no-activities component with passed-in attribute
None.
=> Pass upcoming weeks limit from LMS.

features/workToDo/d2l-w2d-collections.js, features/workToDo/lang/en-us.js, features/workToDo/lang/en.js
Add description for screen readers.
See ticket: [DE43323](https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fdefect%2F601504099748&view=aea56dea-ee73-4c07-9842-cc15d4efc0ea&fdp=true?fdp=true): 3. Screen reader announcing number of activties
- Add sr-only text using `aria-label`
- Hide original text from screen reader using `aria-hidden`
None.
=> Add screen reader only text.

features/workToDo/w2dSummonActionObserver.js
As part of adding the new W2D component to Brightspace for Parents, we need to be able to change the date range W2D is showing, as this was a feature of the old upcoming work widget in BfP. W2D mostly works in this regard, but it doesn't fetch the new date range when an updated start/end date is set on it. This change resolves that by re-fetching whenever these parameters change.
This also includes a minor refactor by moving some common behaviour into `_fetchRoutedState`, as it was needed by two existing functions, as well as the two new ones.
=> US128094 Add start/end date observers

features/workToDo/d2l-w2d-collections.js, features/workToDo/d2l-w2d-no-activities.js
The "View All Work" button is being correctly hidden [in `d2l-w2d-collections`](https://github.com/BrightspaceHypermediaComponents/foundation-components/blob/65c3e3a7544907be18ed4a05b92b59a40af50667/features/workToDo/d2l-w2d-collections.js#L294) when the `dataFullPagePage` is not set. This just adds similar behavior to the empty state `d2l-w2d-no-activities` component, so that it doesn't display a "View All Work" button if there is nowhere for the button to go.
=> Hide "View All Work" button from empty state

components/activity/code/test/d2l-activity-code-editor.test.js, test/testTemplate.js
```Context```
I had an idea of creating generic testing data that could be reused for components, but thinking this is more confusing / complex than it should be. In addition the AddMock util was only good for learning paths use case. Defining mocks inside the tests with the data seems to be a better approach, so I am updated the testTemplate and started to cleanup the tests.
Leaving the PR where it is for now to discuss if this is the approach we should follow.
=> Testing strategy for components

features/workToDo/d2l-w2d-collections.js, features/workToDo/test/d2l-w2d-work-to-do.test.js, test/data/workToDo.js
6 or less | 7 or more
-------|-------
Only show the "View all work" button if there are at least 7 items.
See ticket: [DE43688](https://rally1.rallydev.com/#/515253241784ud/workviews?detail=%2Fdefect%2F605810430964&fdp=true?fdp=true): W2D widget on course page always shows View All Work link
- Add conditional to "View all work" button to only display if page total is greater than page size.
- Add a test that will fail if this behaviour stops.
None.
=> Only show the "View all work" button if there are at least 7 items.

components/activity/editor/collection/d2l-activity-editor-collection-add.js, karma.sauce.conf.js
[DS11220](https://rally1.rallydev.com/#/357252966636d/dashboard?detail=%2Fdefectsuite%2F602692795579&fdp=true?fdp=true): Learning paths >20.21.5 >  Unable to add Activities to Learning Path
Small PR that will fix search's behavior in the activity collection editor.
Foundation engine caches entity responses based on the URL. Because this search provides its query through the body of the request, the URL is always the same, so you always get the same search results.
This change un-caches the results from search, such that the same URL will be able to provide different results when searching.
Since the Load More Summon Action's URLs have a small chance to also coincidentally be searched from, I uncached it as well to make sure we won't need to come back and change it in the future. Please …
=> fix: Add caching to search and load more

features/workToDo/d2l-w2d-collections.js, features/workToDo/w2dDateCategoryObserver.js
When the `startDate` and `endDate` on the component changes, it should re-fetch W2D based on that new date range, and display the W2D items for that date range. This is useful for e.g. in BfP, where we only ever show two weeks at a time.
Previously, data would be re-fetched, but due to nothing necessarily being returned (i.e. no upcoming activities in the specified time range), we wouldn't necessarily replace the contents of `categories` with the new data. Instead, we were basically acting like _only_ the startDate was changing, and would show "W2D from your selected startDate until whatever endDate was when the widget was first created". This is incorrect, though - with both start and end date set, we should show _only_ W2D from that date range (grouped and paged as required).
The change …
=> DE44473 Fix date changing behaviour

features/workToDo/d2l-w2d-attribute-list.js, features/workToDo/d2l-w2d-list-item.js
Before | After 
------- | ------
Fix due date being cut off.
See Ticket: [DE44196](https://rally1.rallydev.com/#/515253241784d/custom/367300408400?detail=%2Fdefect%2F602631407919&fdp=true?fdp=true): 1. Work To Do Widget Truncates Date for Long Course Names
- Remove Flex styling.
- Use `span` instead of `div` because these are now inline elements.
- Wrap all in a `div`.
- Add `text-overflow` property to slot.
- Add `vertical-align` property to bullet.
- Balance spacing on both sides of bullet.
None.
=> DE44196 Fix due date being cut off

features/workToDo/d2l-w2d-collections.js, features/workToDo/d2l-w2d-list-item.js, features/workToDo/d2l-w2d-list.js, features/workToDo/d2l-w2d-work-to-do.js
Parent portal needs activities that haven't started yet to still be clickable to I've added an option to do that
https://rally1.rallydev.com/#/378960033600d/workviews?Name=%5BBfP%5D%20Activities%20that%20haven't%20started%20yet%20aren't%20clickable&Priority=Normal&Project=https%3A%2F%2Frally1.rallydev.com%2Fslm%2Fwebservice%2Fv2.x%2Fproject%2F378960033600&Severity=Minor%20Problem&detail=%2Fdefect%2F605126742893&iteration=u&rankTo=BOTTOM&view=dd31669c-8a70-406a-8edf-892fc6f74aef&fdp=true?fdp=true
=> DE44542 - Adds the option for activities that have not started yet to be clickable (needed for parent portal)

features/discover/d2l-discover-rules.js, features/discover/test/d2l-discover-rules.test.js, package.json
Small change to send an additional flag to the BFF when committing for determining the checkbox state. 
Edited the tests to confirm the flag is being set correctly for different values.
=> Update the UI to send the canSetRegister flag

components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js
The dialog callback `activities` param is `undefined` if no questions were updated/saved, so we can return from the callback without performing any updates. Calling `activities.map` was throwing errors when cancelling the dialog.
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F605845103195
=> DE44655 Handle closing quiz item dialog on cancel

features/discover/d2l-discover-rules.js, features/discover/lang/en-us.js, features/discover/test/d2l-discover-rules.test.js
Small fixes for enrollment rules UI: 
- Gets the resolved token and passes it to the non-hmc component `d2l-discover-rule-card` so it has a proper token
- Changes the enrollment rules commit to use the `id` instead of the `type` during rule generation
- Updates tests
=> fix: Get resolved token for simple components

features/workToDo/lang/zh-cn.js
Rally: [US130604](https://rally1.rallydev.com/#/357251704080ud/search?detail=%2Fuserstory%2F605851386413&keywords=Chinese%20WTD&fdp=true?fdp=true)
`zh-cn` was missing a few langterms, including the one for due date - which meant the due date never rendered in any W2D list items if the student had that selected as their language. I compared to `en` and added all the missing langterms so we wouldn't run into the same issue elsewhere in the code.
=> fix: add missing langterms to zh-cn

components/activity/editor/collection/custom/quiz/d2l-activity-collection-editor-quiz.js
The `summon` action appears to have its params changed recently to accept an object for the second arg instead of the single `bypassCache` boolean it was previously. As a result, `_addToCollection` wasn't bypassing the cache correctly when summoning the `start-add-existing-activities` action and the returned collection didn't include the newly added question objects.
https://trello.com/c/uSGfZWcd/445-cannot-create-questions-sections-questionpools-in-face-quizzing-in-the-latest-quad-it-works-in-20219
@tenbradley Would this have been expected to break after the [recent engine changes](https://github.com/BrightspaceHypermediaComponents/foundation-engine/pull/115)? I'm seeing [some instances](https://github.com/BrightspaceHypermediaComponents/foundation-components/blob/59a48cc9d215fbe50a0fdcae …
=> Fix quiz question addToCollection summon action cache bypass

components/activity/editor/collection/custom/quiz/d2l-activity-collection-editor-quiz.js, components/activity/editor/collection/custom/quiz/d2l-activity-collection-item-quiz.js
New question objects (incl sections and pools) are added directly through QED.
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F608666591373
Alongside [d2l-activities PR](https://github.com/BrightspaceHypermediaComponents/activities/pull/1978) and [LMS PR](https://github.com/Brightspace/lms/pull/14093).
=> US131490 Remove add-to-collection logic for importing sketchpad questions

features/discover/mixins/match-count-mixin.js
As part of the recent FE fixes, the summon() function signature has changed:
https://github.com/BrightspaceHypermediaComponents/foundation-engine/blob/9cc4413c66dfdef7550698ced649d5477789476e/state/observable/SirenSummonAction.js#L99
This PR updates the bypass cache flag to match the new method signature.
=> fix: Change the cache argument to match FE changes

features/workToDo/d2l-w2d-work-to-do.js, test/data/workToDo.js
With this change, the intitial request to the LMS will return data. But more importantly, the activities will be cached, so that the second requests to both activities and overdue api don't need to both calculate all activities.
This roughly halves the work that the worktodo widget does on the LMS end.
=> fix: remove #empty in worktodo activities rel to make use of cache 

features/discover/d2l-discover-rule-picker.js
[DE45110](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fdefect%2F608843206171)
After clicking on the "Add another condition", the focus is now on the latest condition rather than remaining on the button previously clicked to improve the accessibility.
=> After adding another condition focus is on new one

features/discover/d2l-discover-rule-picker.js
[DE45032](https://rally1.rallydev.com/#/357252275780d/dashboard?detail=%2Fdefect%2F608078291677)
Switching the property binding from `?selected="${condition.properties.type === conditionType.properties.type}"` to `.selected="${condition.properties.type === conditionType.properties.type}"` reacts the way the AC wants it to.
=> Data correctly displays OrgUnitID

features/lti/d2l-lti-activity.js
=> fix: Fix how the open as external button looks when description is displayed
